### ISSUE TITLE
KafkaSource and KafkaBinding v1beta1 umbrella task 

### ISSUE THREAD

**Issue by aliok** [knative/eventing-contrib#1332]
Similar to the structure at https://github.com/knative/eventing/issues/3411

- [x] 1. Type bumps: https://github.com/knative/eventing-contrib/pull/1294
- [x] 2. Conversion: https://github.com/knative/eventing-contrib/pull/1341
- [x] 3.  Webhook config for defaulting + validation + conversion: https://github.com/knative/eventing-contrib/issues/1346
- [x] 4. Add new version to CRD and update the CRD field descriptions: https://github.com/knative/eventing-contrib/issues/1347
- [x] 5. Update docs and examples: https://github.com/knative/eventing-contrib/issues/1348
- [x] 6. Update e2e tests to use new version: https://github.com/knative/eventing-contrib/issues/1375
- [ ] 7. Make new version the storage version: https://github.com/knative/eventing-contrib/issues/1394
- [x] 8. Migrate reconciler to new version: https://github.com/knative/eventing-contrib/issues/1395
- [ ] 9. Remove old version (long term goal)

**Comment by matzew** [comment]
@aliok what about (in separate PR?) doing the `krshapedlogic` ? 

example: https://github.com/knative/eventing/pull/3226

**Comment by aliok** [comment]
/close

Created tickets in new repo, `knative-sandbox/eventing-kafka` for the remaining tasks: https://github.com/knative-sandbox/eventing-kafka/issues/65

**Comment by aliok** [comment]
> @aliok what about (in separate PR?) doing the krshapedlogic ?
> example: knative/eventing#3226

@matzew , I created https://github.com/knative-sandbox/eventing-kafka/issues/69 for this
