### ISSUE TITLE
KafkaChannel v1beta1 umbrella task

### ISSUE THREAD

**Issue by aliok** [knative/eventing-contrib#1350]
Similar to the structure at https://github.com/knative/eventing/issues/3411

- [x] 1. Type bumps: https://github.com/knative/eventing-contrib/issues/1351
- [x] 2. Conversion: https://github.com/knative/eventing-contrib/issues/1352
- [x] 3.  Webhook config for defaulting + validation + conversion: https://github.com/knative/eventing-contrib/issues/1353
- [x] 4. Add new version to CRD and update the CRD field descriptions: https://github.com/knative/eventing-contrib/issues/1354
- [x] 5. Update docs and examples: https://github.com/knative/eventing-contrib/issues/1355
- [x] 6. Update e2e tests to use new version: https://github.com/knative/eventing-contrib/issues/1376
- [ ] 7. Make new version the storage version: https://github.com/knative/eventing-contrib/issues/1396
- [ ] 8. Migrate reconciler to new version: https://github.com/knative/eventing-contrib/issues/1397
- [ ] 9. Remove old version (long term goal)

**Comment by aliok** [comment]
/close

Created tickets in knative-sandbox/eventing-kafka for the remaining work: https://github.com/knative-sandbox/eventing-kafka/issues/70
