### ISSUE TITLE
Upgrade GitHubSource to v1beta1 umbrella task

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#1387]
Here the list of tasks to upgrade  GitHubSource to v1beta1 :

 - [ ] Implement v1beta1 types for GitHubSource resource.
 - [ ] Add new version to CRD 
  - [ ] update the CRD field descriptions  
   - [ ] Update docs and examples
   - [ ] Update e2e tests to use v1beta1 
   - [ ] Make v1bveta1 the storage version
   - [ ] Migrate reconciler to v1beta1
   - [ ] Remove v1alpha1 (long term goal)

**Comment by lionelvillard** [comment]
Here the proposed list of changes:
- Remove ServiceAccountName 
- Make secret optional: https://github.com/knative/eventing-contrib/issues/297

**Comment by lionelvillard** [comment]
moved there: https://github.com/knative-sandbox/eventing-github/issues/64
