### ISSUE TITLE
Splitting this repo to smaller knative-sandbox repos (umbrella issue)

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#1482]
The issue describes both the process and where individual components should be moved to.

## Process

1. Open an issue requesting the creation of a new repo: https://github.com/knative/community/issues/new/choose
1. Wait for the repository to be created 
1. Push eventing-contrib to the new remote:

    ```shell
        cd eventing-contrib
        git remote add newrepo https://github.com/knative-sandbox/newrepo.git
        git push newrepo
    ```

1. Cleanup: fork the repo and create a PR
     - delete everything not related to newrepo
     - update hack/release.sh
     - update hack/update-codegen.sh
     - update hack/update-deps.sh
     - update go.mod module to be knative.dev/newrepo
     - rename knative.dev/eventing-contrib/<component>/... packages to knative.dev/newrepo/... Move code accordingly to match the other repo structure
     - remove OWNERS files in subdirectories. Only keep the top-level one
     - cleanup OWNES_ALIASES
     - edit README.md
     - run hack/release.sh and make sure it produces the proper artifacts
     - update .github/workflows/knative-downstream.yaml
1. Remove the component from eventing-contrib

## Components

This tracks the components to be moved, where they should moved and who should do it (based on the current owners).

- [x] [awssqs](https://github.com/knative/eventing-contrib/tree/master/awssqs) -> `eventing-awssqs`  (@lberk)
    - [x] [repo request](https://github.com/knative/community/issues/232)
    - [x] Push eventing-contrib
    - [x] Cleanup newrepo
    - [x] Cleanup eventing-contrib
    - [x] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)
- [ ] [camel](https://github.com/knative/eventing-contrib/tree/master/camel) -> `eventing-camel` (@nicolaferraro, @matzew)
    - [x] [repo request](https://github.com/knative/community/issues/233)
    - [x] Push eventing-contrib
    - [x] Cleanup newrepo
    - [x] Cleanup eventing-contrib
    - [ ] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)
- [x] [ceph](https://github.com/knative/eventing-contrib/tree/master/ceph) -> `eventing-ceph` (@lberk?)
    - [x] [repo request](https://github.com/knative/community/issues/234)
    - [x] Push eventing-contrib
    - [x] Cleanup newrepo
    - [x] Cleanup eventing-contrib
    - [x] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)
- [ ] [couchdb](https://github.com/knative/eventing-contrib/tree/master/couchdb) -> `eventing-couchdb` (@lionelvillard)
    - [x] [repo request](https://github.com/knative/community/issues/224)
    - [x] Push eventing-contrib
    - [x] Cleanup newrepo
    - [x] Cleanup eventing-contrib
    - [x] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)
- [ ] [github](https://github.com/knative/eventing-contrib/tree/master/github) -> `eventing-github` (@lionelvillard)
   - [x] [repo request](https://github.com/knative/community/issues/223)
   - [x] Push eventing-contrib
   - [x] Cleanup newrepo
   - [x] Cleanup eventing-contrib
   - [x] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)
- [ ] [gitlab](https://github.com/knative/eventing-contrib/tree/master/gitlab) -> `eventing-gitlab` (@sebgoa, @tzununbekov)
    - [x] [repo request](https://github.com/knative/community/issues/235)
    - [x] Push eventing-contrib
    - [x] Cleanup newrepo
    - [x] Cleanup eventing-contrib
    - [x] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)
- [ ] [kafka](https://github.com/knative/eventing-contrib/tree/master/kafka) -> ? (@lberk, @matzew)
    
- [ ] [natss](https://github.com/knative/eventing-contrib/tree/master/natss) -> `eventing-natss`  (@devguyio)
    - [x] [repo request](https://github.com/knative/community/issues/236)
    - [x] Push eventing-contrib
    - [x] Cleanup newrepo
    - [ ] Cleanup eventing-contrib
    - [ ] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)
- [x] [prometheus](https://github.com/knative/eventing-contrib/tree/master/prometheus) -> `eventing-prometheus` (@syedriko, @matzew)
    - [x] [repo request](https://github.com/knative/community/issues/237)
    - [x] Push eventing-contrib
    - [x] Cleanup newrepo
    - [x] Cleanup eventing-contrib
    - [x] Setup [automated releases](https://github.com/knative/test-infra/blob/master/guides/release_setup.md#setting-up-automated-releases)

Please add your comments below and I'll update the process and component list accordingly. 

@n3wscott @vaikas @grantr @nachocano @Harwayne

**Comment by lionelvillard** [comment]
@matzew @davyodom @lberk Can we move the kafka bits over to `knative-sandox/eventing-kafka`? IMO it's fine to have 2 different implementations there.

**Comment by lionelvillard** [comment]
@mattmoor @lberk I can take care of moving the GitHub code over.

**Comment by davyodom** [comment]
It feels strange to split apart eventing-contrib but combine separate kafka implementations together in a different place. We'll then face the same pain (dependency management, etc) which is trying to be alleviated by splitting eventing-contrib apart.  If it is decided to take this approach it would take some effort to make these two things exist together coherently in the eventing-kafka repo I think.

**Comment by lionelvillard** [comment]
> We'll then face the same pain

Well not quite (I hope). It's one thing to have 10 (and counting) different components in one repo vs only 2. 

I don't have strong feelings about it, other people can jump in and give their opinion. Personally I find our Kafka story quite confusing, with no clear reason why to pick one implementation vs the other, since both are now using the same library. Having only one repo would help straighten the story, especially for people going straight to GitHub (vs reading the doc first).

**Comment by matzew** [comment]
I'd think that we move the current kafka source and kafka channel to something like "knative/eventing-kafka" repo.

If we feel like adding a second implementation approach of a channel, using the same APIs, why not ? 
I think if the channels have different goals and philosophies and therefore is reasonable to have both.

Now, with the kafka client being the same, I think it may make sense, at somepoint to see if - eventually - it really makes sense to merge the two channels - or use some of their impl. for other ideas like sink (real sinks, as in CRDs)

IMO it's bad if we now just pick one, to only have one.... the benefit of a sandbox repo is to have independent room for exploring ideas

**Comment by davyodom** [comment]
Agreed on the general points here.  Perhaps we can discuss in the next delivery WG meeting further?  If we do combine the two channels into one repo and also the source, we probably need to do some restructuring (extract common packages like the API, client and its configuration?, etc).  Some probably mandatory as a first step, so builds and releases still work, and other refactoring could be done afterwards.

**Comment by slinkydeveloper** [comment]
For what regards kafka, i think atm we're not ready to host both projects in the same repo.

Also, i think the kafka impl in eventing-contrib should continue to live under `knative` org, since it's a "mature" project of the knative umbrella. I would say the same for gitlab, github, camel and other sources that are under `eventing` since quite some time... Moving them to knative-sandbox seems like "degraduating" them to unstable projects
